<a href="https://colab.research.google.com/github/Krishna101211/NUMPY/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array([1,2,3,4,5])

In [ ]:
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(x.itemsize)
print(x.nbytes)
print(x.real)

1
(5,)
5
int64
8
40
[1 2 3 4 5]


In [ ]:
u=np.array([1+2j,8+9j])
print(u)

[1.+2.j 8.+9.j]


In [ ]:
print(x.real)#property
print(x.imag)#property

[1 2 3 4 5]
[0 0 0 0 0]


In [ ]:
y=np.array([[1,2,3,4],[4,5,6,7]])
print(y)

[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
print(y.shape)
print(y.T)#transpose

(2, 4)
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [ ]:
#type() vs dtype()


In [ ]:
k=np.array([[1,2,3,4,5],[4,5,6,7,8]])
#k[1]='abc'#ValueError: invalid literal for int() with base 10: 'abc'

In [ ]:
# print(k[4])

In [ ]:
print(k[1][2])

6


In [ ]:
s=[1,2,3,4,5]

In [ ]:
q=s.copy()


In [ ]:
print(id(q))
print(id(q))

133950271143680
133950271143680


In [ ]:
q[2]=[200]

In [ ]:
print(q)

[1, 2, [200], 4, 5]


In [ ]:
print(s)

[1, 2, 3, 4, 5]


In [ ]:
o=np.array([1,2,3,4,5])
O=o.view()

****

In [ ]:
print(id(O))
print(id(o))

133950267114960
133950267119472


Copy:
A copy creates a new array with its own independent data.
It resides in a separate memory location from the original array.
Changes made to the copy will not affect the original array, and vice-versa.
You explicitly create a copy using the .copy() method or by performing operations that inherently create copies (e.g., advanced indexing).

View:
A view creates a new array object that shares the same data as the original array.
It essentially provides a different perspective or "window" into the same memory location as the original array.
Changes made to the view will affect the original array, and vice-versa, because they are referencing the same underlying data.
Views are often created implicitly by certain NumPy operations like slicing or reshaping, and explicitly using the .view() method.

In [ ]:
d=np.array([[2,3,4,4,5],[123,4454,55,55,22]])

In [ ]:
Q=d.flatten()#

In [ ]:
print(Q)

[   2    3    4    4    5  123 4454   55   55   22]


In [ ]:
Q=d.flatten(order='C')#
print(Q)

[   2    3    4    4    5  123 4454   55   55   22]


In [ ]:
Q=d.flatten(order='F')

In [ ]:
print(Q)

[   2  123    3 4454    4   55    4   55    5   22]
