<a href="https://colab.research.google.com/github/Krishna101211/NUMPY/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3,4],[4,5,6,6]])

In [ ]:
a

array([[1, 2, 3, 4],
       [4, 5, 6, 6]])

#**RESHAPE()**

In [ ]:
a.reshape(8,1)#use to chaneg the shape of array multidimensional to single dimension
#what ever number we pass should match number present in  array

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [6]])

In [ ]:
print(a.ndim)

2


In [ ]:
a.reshape(1,8)

array([[1, 2, 3, 4, 4, 5, 6, 6]])

In [ ]:
a.reshape(-1)#ine dimension

array([1, 2, 3, 4, 4, 5, 6, 6])

#**FLATTEN()**

In [ ]:
b=np.array([[1,2,3,4],[4,5,6,6]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 6]])

In [ ]:
b.flatten()#to convert multidimension to single dimenstion by defalut convert based on rows format
#act like immutable

array([1, 2, 3, 4, 4, 5, 6, 6])

In [ ]:
b[0]=100
b

array([[100, 100, 100, 100],
       [  4,   5,   6,   6]])

In [ ]:
o=b.flatten()
o[0]=100
o

array([100, 100, 100, 100,   4,   5,   6,   6])

In [ ]:
b.reshape(-1)

array([1, 2, 3, 4, 4, 5, 6, 6])

In [ ]:
b.flatten(order='C')

array([1, 2, 3, 4, 4, 5, 6, 6])

In [ ]:
b.flatten(order='F')#column format shaping

array([1, 4, 2, 5, 3, 6, 4, 6])

#**RAVEL()**

In [ ]:
v=np.array([[1,2,3,4],[4,5,6,6]])
v

array([[1, 2, 3, 4],
       [4, 5, 6, 6]])

In [ ]:
v.ravel()

array([1, 2, 3, 4, 4, 5, 6, 6])

In [ ]:
v.ravel(order='c')#row format

array([1, 2, 3, 4, 4, 5, 6, 6])

In [ ]:
v.ravel(order='F')#column format

array([1, 4, 2, 5, 3, 6, 4, 6])

In [ ]:
d=v.ravel()
d[0]=111
d

array([111,   2,   3,   4,   4,   5,   6,   6])

#**REPEAT()**

In [ ]:
R=np.array([1,2,3,4])

In [ ]:
np.repeat(R,3)#elements will repeat

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

**TILE(VAR_NAME,NO.REPEAT)**

In [ ]:
np.tile(R,4)#complete array will repeat

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

#**ITEM()**

In [ ]:
q=np.array([1,2,3,4])
q

array([1, 2, 3, 4])

In [ ]:
q.item(3)

4

In [ ]:
#q.itemset(1,200)#AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.

In [ ]:
q.take(1)

np.int64(2)

In [ ]:
q.take([1,2,3])

array([2, 3, 4])

**PUT()**

In [ ]:
E=np.array([[1,2,3,4],[1,2,3,4]])
E

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
E.put([1,2,3],[100,200,300])#replacement of itemset()
E

array([[  1, 100, 200, 300],
       [  1,   2,   3,   4]])

In [ ]:
E.put([5,6,7],[100,200,300])
E

array([[  1, 100, 200, 300],
       [  1, 100, 200, 300]])

In [ ]:
E.put((5,6,7),[2,3,4])
E

array([[  1, 100, 200, 300],
       [  1,   2,   3,   4]])

#**ARANGE()** pronunce like a range

In [ ]:
#print the sequence of number syntax smilar to slicing
#in normal range() we cant use decimal number
# it will not generate 50 numbers by default

In [ ]:
t=np.arange(5)
t

array([0, 1, 2, 3, 4])

In [ ]:
l=np.arange(1.1,2.2,3.3)
l

array([1.1])

In [ ]:
l=np.range(1.1,2.2,3.3)#AttributeError: module 'numpy' has no attribute 'range'

#**LINSPACE()**

In [ ]:
P=np.linspace(0,10,num=5)#to print the sequence of number
#we didnt mention num=5 by default it will generate 50 number
P

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
P=np.linspace(0,10,num=5,retstep=True)
P

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))