<a href="https://colab.research.google.com/github/Krishna101211/NUMPY/blob/main/3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#**ZEROS()**

In [2]:
a=np.zeros(1)
a

array([0.])

**zeros((number),dtype=)** `
by default it will give o/p in float and for dimension go with ()

In [5]:
a=np.zeros(4,dtype=int)
a

array([0, 0, 0, 0])

In [4]:
a=np.zeros(4,dtype=complex)
a

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [6]:
a=np.zeros((2,3),dtype=complex)
a

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

#**ones()**

In [7]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

by default o/p is in float

In [8]:
a=np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#**full()**

In [10]:
x=np.full((2,2),10)
x

array([[10, 10],
       [10, 10]])

In [13]:
x=np.full((2,2),"numpy")
x

array([['numpy', 'numpy'],
       ['numpy', 'numpy']], dtype='<U5')

#**where(v_n==value_to_find)**
#**unique(v_name,property)**

In [15]:
v=np.array([1,2,3,3])

In [22]:
k=np.where(v==10)
k

(array([], dtype=int64),)

In [19]:
d=np.where(v==1)
d

(array([0]),)

In [21]:
p=np.unique(v)
p

array([1, 2, 3])

In [23]:
pl=np.unique(v,return_index=True)
pl

(array([1, 2, 3]), array([0, 1, 2]))

In [24]:
plx=np.unique(v,return_counts=True)
plx

(array([1, 2, 3]), array([1, 1, 2]))

#**array_split()**
syntax=nev_v_n=array.split(old_new,sections)

In [25]:
k=np.array([10,23,45,10,45,89,99,100,200,100])

In [27]:
e=np.array_split(k,15)#use to individual seprate groups
e

[array([10]),
 array([23]),
 array([45]),
 array([10]),
 array([45]),
 array([89]),
 array([99]),
 array([100]),
 array([200]),
 array([100]),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64)]

#**diagonal matrix**
eye()

identity()

In [ ]:
h=np.array([10,23,45,10,45,89,99,100,200,100])

In [29]:
i=np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
i=np.eye(3,k=1)#k property used to move diagonal
i

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [31]:
i=np.eye(3,k=3)
i

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
i=np.eye(3,k=-1)#ValueError: negative dimensions are not allowed
i

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
#in identity we cant change diagonal place

In [34]:
l=np.identity(3)
l

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#**diag()**

In [35]:
j=np.diag([1,2,3],k=0)
j

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [37]:
j=np.diag([1,2,3],k=1)
j

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [36]:
j=np.diag([1,2,3],k=2)
j

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
j=np.diag([1,2,3],k=-1)
j

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])