<a href="https://colab.research.google.com/github/Krishna101211/NUMPY/blob/main/5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np



# **intersected1d() union1d() setdiff1d() setxor1d() in1d()**

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
a,b

(array([1, 2, 3, 4, 5]), array([3, 4, 5, 6, 7]))

after performing operation we get o/p in sorted format,by default ascending

In [5]:
x=np.intersect1d(a,b)
x

array([3, 4, 5])

In [6]:
y=np.union1d(a,b)
y

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
z=np.setdiff1d(b,a)
Z=np.setdiff1d(a,b)
z,Z

(array([6, 7]), array([1, 2]))

In [9]:
w=np.in1d(a,b)#comman element---> True and unique element--->False
w

/tmp/ipython-input-3294971704.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  w=np.in1d(a,b)#comman element---> True and unique element--->False


array([False, False,  True,  True,  True])

In [10]:
W=np.isin(a,b)
W

array([False, False,  True,  True,  True])

In [11]:
k=np.setxor1d(a,b)
k

array([1, 2, 6, 7])

#**sum() prod() mean() std() var() min() max()**

#**argmin()argmax()**

#**cumsum() cumprod()**

In [28]:
p=np.array([1,20,13,4,5])

In [15]:
p.sum()

np.int64(15)

In [16]:
p.prod()

np.int64(120)

In [17]:
p.mean()

np.float64(3.0)

In [18]:
p.std()

np.float64(1.4142135623730951)

In [19]:
p.var()

np.float64(2.0)

In [20]:
p.min()

np.int64(1)

In [21]:
p.max()

np.int64(5)

In [22]:
p.argmin()

np.int64(0)

In [23]:
p.argmax()

np.int64(4)

In [31]:
l=p.argsort()#o/p will get the index
l

array([0, 1, 2, 3, 4])

In [35]:
p.sort()
p

array([ 1,  4,  5, 13, 20])

In [26]:
p.cumsum()

array([ 1,  3,  6, 10, 15])

In [27]:
p.cumprod()

array([  1,   2,   6,  24, 120])

#**for 2-dimension**

In [36]:
f=np.array([[4,3,2],[5,3,9]])
f

array([[4, 3, 2],
       [5, 3, 9]])

In [38]:
s=f.sum()
S=f.sum(axis=0)#add only based on column
Ss=f.sum(axis=1)
s,S,Ss

(np.int64(26), array([ 9,  6, 11]), array([ 9, 17]))

In [40]:
g=f.prod()
G=f.prod(axis=0)
Gg=f.prod(axis=1)
g,G,Gg

(np.int64(3240), array([20,  9, 18]), array([ 24, 135]))

In [41]:
v=f.mean()
V=f.mean(axis=0)
Vv=f.mean(axis=1)
v,V,Vv

(np.float64(4.333333333333333),
 array([4.5, 3. , 5.5]),
 array([3.        , 5.66666667]))

In [43]:
n=f.std()
N=f.std(axis=0)
Nn=f.std(axis=1)
n,N,Nn


(np.float64(2.2852182001336816),
 array([0.5, 0. , 3.5]),
 array([0.81649658, 2.49443826]))

In [44]:
j=f.var()
J=f.var(axis=0)
Jj=f.var(axis=1)
j,J,Jj

(np.float64(5.222222222222222),
 array([ 0.25,  0.  , 12.25]),
 array([0.66666667, 6.22222222]))

In [45]:
m=f.min()
M=f.min(axis=0)
Mm=f.min(axis=1)
m,M,Mm

(np.int64(2), array([4, 3, 2]), array([2, 3]))

In [46]:
l=f.max()
L=f.max(axis=0)
Ll=f.max(axis=1)
l,L,Ll

(np.int64(9), array([5, 3, 9]), array([4, 9]))

In [47]:
h=f.argmin()
H=f.argmin(axis=0)
Hh=f.argmin(axis=1)
h,H,Hh

(np.int64(2), array([0, 0, 0]), array([2, 1]))

In [48]:
k=f.argmax()
K=f.argmax(axis=0)
Kk=f.argmax(axis=1)
k,K,Kk

(np.int64(5), array([1, 0, 1]), array([0, 2]))

In [49]:
p=f.cumsum()
P=f.cumsum(axis=0)
Pp=f.cumsum(axis=1)
p,P,Pp

(array([ 4,  7,  9, 14, 17, 26]),
 array([[ 4,  3,  2],
        [ 9,  6, 11]]),
 array([[ 4,  7,  9],
        [ 5,  8, 17]]))

In [50]:
r=f.cumprod()
R=f.cumprod(axis=0)
Rr=f.cumprod(axis=1)
r,R,Rr

(array([   4,   12,   24,  120,  360, 3240]),
 array([[ 4,  3,  2],
        [20,  9, 18]]),
 array([[  4,  12,  24],
        [  5,  15, 135]]))

#**Complex method**

In [51]:
y=np.array([34+5j,-67-6j,12+5j,-89-34j])
y

array([ 34. +5.j, -67. -6.j,  12. +5.j, -89.-34.j])

In [56]:
z=y.real
z

array([ 34., -67.,  12., -89.])

In [55]:
k=y.imag
k

array([  5.,  -6.,   5., -34.])

In [57]:
h=y.conj()
h

array([ 34. -5.j, -67. +6.j,  12. -5.j, -89.+34.j])

#**Searchsorted(num,side)** side is not mandotary

In [59]:
f=np.array([10,20,30,40,50])
f

array([10, 20, 30, 40, 50])

In [66]:
k=f.searchsorted(20,side="left")
krus=f.searchsorted(20,side="right")
k,krus

(np.int64(1), np.int64(2))

In [67]:
count=f.searchsorted(220,side="left")
count

np.int64(5)